[package]
name = "soulful-companion"
version = "0.1.0"
authors = ["twtc <raner.piibur@gmail.com>"]

[dependencies]
timer = "0.1.6"
chrono = "0.3.0"
serde = "1.0.2"
serde_yaml = "0.7.0"
serde_derive = "1.0.2"